### ISSUE TITLE
Add license to repo

### ISSUE THREAD

**Issue by michael-sbarra-apexai** [phpisciuneri/rules-openblas#1]
Hi, I would like to use this Bazel rule in a private/proprietary Bazel project. However, because this project doesn't have a permissive license (BSD, MIT, Apache 2.0), let alone any license, I am unable to do so. Could you please add a license to the project, ideally a permissive one?

**Comment by phpisciuneri** [comment]
I added Apache 2.0 license and created a new release: https://github.com/phpisciuneri/rules_openblas/releases/tag/v0.1.3
